// Generated by CoffeeScript 1.4.0
(function() {
  var moveOutOfHoldingPen, showDebugColors;

  $(function() {
    return moveOutOfHoldingPen();
  });

  moveOutOfHoldingPen = function() {
    return $("div#holding-pen").children('div').each(function() {
      var new_parent;
      new_parent = $("div#" + ($(this).attr('id')) + "-parent");
      return $(this).detach().appendTo(new_parent);
    });
  };

  showDebugColors = function() {
    var color, colors, _i, _len, _results;
    colors = ['blue', 'green', 'red', 'yellow', 'purple', 'orange'];
    _results = [];
    for (_i = 0, _len = colors.length; _i < _len; _i++) {
      color = colors[_i];
      _results.push($(".test-" + color).css({
        backgroundColor: color
      }));
    }
    return _results;
  };

}).call(this);
