application: google.com:expert
version: 3
runtime: python
api_version: 1
# threadsafe: false

handlers:
- url: /static
  static_dir: static

- url: /javascript
  static_dir: javascript

- url: /manageAccount
  login: required
  script: guru.py

- url: /signUp
  login: required
  script: guru.py

- url: /calendarCrons
  login: admin
  script: guru.py

- url: /admin/.*
  login: admin
  script: guru.py

- url: /.*
  login: required
  script: guru.py
  
# libraries:
# - name: django
#   version: "1.2"

inbound_services:
- channel_presence
- xmpp_error
- xmpp_message
- xmpp_presence
- xmpp_subscribe

