application: google.com:expert
version: 2
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /manageAccount
  login: required
  script: guru.py

- url: /admin/.*
  login: admin
  script: guru.py

- url: /.*
  script: guru.py



inbound_services:
- xmpp_message
- xmpp_presence
- xmpp_subscribe

